spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/orders_db
        username: postgres
        password: password
    jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
    rabbitmq:
        host: localhost
        port: 5672